apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-avatars-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb-media
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: smb-avatars-volume
    volumeAttributes:
      source: "//192.168.1.3/Media_TT/media/avatars"
    nodeStageSecretRef:
      name: smb-media-secret
      namespace: default
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1001
    - gid=1001
    - vers=3.0