apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-media-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: smb-media
  volumeName: smb-media-pv