"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
import sys

# ============================================================
# 1. СНАЧАЛА ОПРЕДЕЛЯЕМ BASE_DIR (это обязательно!)
# ============================================================
BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# 2. ТЕПЕРЬ ИМПОРТИРУЕМ И НАСТРАИВАЕМ environ
# ============================================================
try:
    import environ
    env = environ.Env()
    # Читаем .env файл из корня проекта (теперь BASE_DIR определен)
    environ.Env.read_env(os.path.join(BASE_DIR, '.env'))
    USE_ENVIRON = True
except ImportError:
    # Если environ не установлен — используем fallback
    USE_ENVIRON = False
    print("⚠️ django-environ не установлен, используем стандартные настройки")


# ============================================================
# 3. SECRET KEY (с поддержкой .env и fallback)
# ============================================================
if USE_ENVIRON:
    SECRET_KEY = env('SECRET_KEY', default='django-insecure-default-key-for-dev')
else:
    # Fallback для разработки (если нет .env)
    SECRET_KEY = 'django-insecure-default-key-for-dev'


# ============================================================
# 4. DEBUG (безопасный, по умолчанию False в продакшене)
# ============================================================
if USE_ENVIRON:
    DEBUG = env.bool('DEBUG', default=True)
else:
    DEBUG = True  # Для разработки


# ============================================================
# 5. ALLOWED_HOSTS (с поддержкой .env)
# ============================================================
if USE_ENVIRON:
    ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['192.168.1.171', 'localhost', '127.0.0.1', '0.0.0.0', '*'])
else:
    ALLOWED_HOSTS = [
        '192.168.1.171',
        'localhost',
        '127.0.0.1',
        '0.0.0.0'
        '*',
    ]


# ============================================================
# 6. Application definition
# ============================================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gallery',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ============================================================
# 7. Database (с поддержкой PostgreSQL для Docker)
# ============================================================
# Проверяем, запущены ли тесты (используем SQLite для тестов)
if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }
else:
    # Для разработки и продакшена
    if USE_ENVIRON and env.bool('USE_POSTGRES', default=False):
        # Используем PostgreSQL (для Docker)
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': env('DB_NAME', default='mydb'),
                'USER': env('DB_USER', default='myuser'),
                'PASSWORD': env('DB_PASSWORD', default='mypassword'),
                'HOST': env('DB_HOST', default='db'),
                'PORT': env('DB_PORT', default='5432'),
            }
        }
    else:
        # Используем SQLite (по умолчанию)
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }


# ============================================================
# 8. Password validation
# ============================================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ============================================================
# 9. Internationalization
# ============================================================
LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_TZ = True


# ============================================================
# 10. Static files (CSS, JavaScript, Images)
# ============================================================
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'


# ============================================================
# 11. Email
# ============================================================
MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# ============================================================
# 12. Default primary key field type
# ============================================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================================
# 13. Для загрузки файлов (аватары, фото)
# ============================================================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ============================================================
# 14. Редиректы после входа/выхода
# ============================================================
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# ============================================================
# 15. Кодировка
# ============================================================
DEFAULT_CHARSET = 'utf-8'
